services:
  postgres:
    image: postgres:latest
    container_name: postgres_container
    environment:
      POSTGRES_USER: your_db_user
      POSTGRES_PASSWORD: your_db_password
      POSTGRES_DB: your_db_name
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./aperitivo_REST/dataset/schema.sql:/docker-entrypoint-initdb.d/1_schema.sql
      - ./aperitivo_REST/dataset/data.sql:/docker-entrypoint-initdb.d/2_data.sql

volumes:
  pgdata:
